
export const metadata = {
  title: 'Blog Detail',
  description: 'Generated by Liti',
}

export default function ViewDetailLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
          {children}
    </>
  )
}
